apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: s79cyw448-go 
  janus-idp.io/tekton: s79cyw448-go
  backstage.io/kubernetes-id: s79cyw448-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s79cyw448-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml